version = 0.1
[default.deploy.parameters]
stack_name = "papernewsletter"
resolve_s3 = true
s3_prefix = "papernewsletter"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"prod\" SubLandingPage=\"insertlandingpage.com" SenderEmail=\"Insert Newsletter Name <newsletter@example.com>\" AlertEmail=\"your.email@example.com\" UseDomainIdentity=\"true\" DomainName=\"newsletter.example.com\" HostedZoneId=\"ZXXXXXXXXXX\" ApiGatewayId=\"xxxxxxxxxxxx\"EmailTestMode=\"true\" EmailTestAddress=\"aipapernewsletter@gmail.com\""
image_repositories = []